config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get '/about-us', to: "pages#about_us"
  get '/sign-up', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users, except: [:new]
  resources :activities do 
    resources :reviews
  end
  resources :categories
  resources :favorites
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user

    has_and_belongs_to_many :categories 
    has_many :reviews
    has_many :favorites
    
    
    validates :name, presence: true, length: {minimum: 2, maximum: 200}
    validates :description, presence: true, length: {minimum: 2, maximum: 400}

    validate :image_path_exists

    def image_path_exists
        
        require 'open-uri'

        begin
            #is url valid 
            #if thrown and exception then rescue will execute 
            path = URI.open(image_path)
            #is response type content image? 
            errors.add(:image_path, "Does not contain image content.") and return unless path.content_type.starts_with?("image")
            
        rescue 
            errors.add(:image_path, "Invalid URL")
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :activities 
    
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, uniqueness: {scope: :activity_id}
  belongs_to :user
  belongs_to :activity
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, :email, presence: true, uniqueness: true, length: {minimum: 3, maximum: 20}
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}
    has_secure_password
    
    has_many :activities 
    has_many :reviews
    has_many :favorites
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[ show edit update destroy ]

  # GET /favorites or /favorites.json
  def index
    @favorites = Favorite.all
  end


  # POST /favorites or /favorites.json

  def create
    @favorite = helpers.current_user.favorites.new(favorite_params)
    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorites_url, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @favorite }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end

  end
  
  # DELETE /favorites/1 or /favorites/1.json
  def destroy
    @activity = @favorite.activity
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: "Favorite was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :activity_id)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @countries = Country.all 
  end

  def about_us
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = helpers.current_user.reviews.new(review_params)
    activity = Activity.find(params[:activity_id])
    @review.activity_id = params[:activity_id]
    respond_to do |format|
      if @review.save
        format.html { redirect_to activity, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to activity_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:content, :date, :activity_id, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_signed_in?, except: [:destroy]
#GET login Page
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Login Successful"
      redirect_to root_path
    else 
      flash[:notice] = "Login Failed"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy 
    session[:user_id] = nil 
    flash[:notice] = "Logout successful."
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_signed_in?, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Account Successfully Created"
      redirect_to user_path 
    else 
      flash[:notice] = "Account Creation Error"
      render :new, status: :unprocessable_entity 
    end
  end

  def show 
    @user = User.find(params[:id])
  end

  def show_reviews
    @user = User.find(params[:id])
  end

  private 
  def user_params 
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    def current_user 
        User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewLeaf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application","data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/nav'%>
  <% if flash[:notice]%>
    <%= flash[:notice]%>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<%= stylesheet_link_tag 'about'%>
<div class = "all">
<div class="about" style="background-color: white; margin-top: 20px">
<div style="display: flex;">
  <div style="flex: 1; margin-right: 10px; margin-top: 5%; padding: 2em">
    <div class="about_text">About Us</div>
    <hr>
      <h1><b>leaf the world be</b></h1>
      <h3> New leaf is an informational website designed to help people be more aware of what they can do to help slow down climate change.</h3>
      <%= link_to "See More", root_path, class:"btn btn-outline-secondary"%>
  </div>
  <div style="flex: 1; margin-left: 10px">
    <img 
    src="https://img.freepik.com/free-vector/reforestation-concept-illustration_114360-8754.jpg?w=900&t=st=1677905081~exp=1677905681~hmac=0154df10f99d57c45a0b2d10649f6b50f541c081fc314285869c2ae39be15f00" 
    class="img-fluid" alt="..." 
    style= "width:100%">
    </div>
</div>
</div>
</div>

app/views/pages/home.html.erb
<div style= "position: relative">
<img 
   src="https://img.freepik.com/free-vector/illustration-people-taking-care-plants_52683-64954.jpg?w=1380&t=st=1677916419~exp=1677917019~hmac=51b11f4ef77ec1d9841203473373d14e53da1175923a3f22b5e76f0daba71aee" 
   class="img-fluid" alt="..." 
   style= "
      width:100%;
      padding: 1em">

   <div
      class="home" 
      style="
         border-style:solid; 
         border-color: #83B692; 
         padding: 1em; 
         width: 30rem; 
         height:15rem; 
         background-color: #53917E; 
         text-align: center; 
         color:white;
         position: absolute; 
         right: 10px; 
         top: 300px; 
         z-index: 1;
         opacity:0.9;">
      <h1>Welcome to New Leaf</h1>
   </div>
</div>

   <h2>What Can You Do?</h2>
   <div class="container">
      <div class="row">
         <% Activity.limit(6).each do |activity| %>
         <div class="col-xs-12 col-md-6 col-lg-4">
         <div class="card" style="width: 18rem;margin-bottom: 30px">
               <div>        
                  <%= link_to activity_path(activity) do%>
                  <%= image_tag activity.image_path, class:"card-img-top", style: "border: 1px solid black" %> 
                  <%end%>
               </div>
               <div class="card-body">
                  <h2><b> <%= activity.name %> </b></h2>
                  <p class="card-text">
                     <p>Description: <%= activity.description.slice(0,10) %>....</p>
                  </p>
               </div>
            </div>
         </div>
         <%end%>
      </div>
   </div>
<%= link_to "Explore More", activities_path%>
<hr>

<div style="text-align: center">
   <h2>Snip of how pollution is affecting our world today</h2>
   <h4>Air quality and pollution city ranking:</h4>
</div>
<div class="row" style="margin-bottom: 30px">
   <div style="padding: 30px; background-color: #01A66F; width: 10%; border-radius: 25%; text-align:center; margin-left: 150px"> Good: 0-50</div>
   <div style="padding: 30px; background-color: #75CE9F; width: 10%; border-radius: 25%; text-align:center; margin-left: 30px">Moderate: 51-100</div>
   <div style="padding: 30px; background-color: #BDD99E; width: 10%; border-radius: 25%; text-align:center; margin-left: 30px">Unhealthy for Some: 101-150</div>
   <div style="padding: 30px; background-color: #FFC06E; width: 10%; border-radius: 25%; text-align:center; margin-left: 30px">Unhealthy: 151-200</div>
   <div style="padding: 30px; background-color: #E2725B; width: 10%; border-radius: 25%; text-align:center; margin-left: 30px">Very Unhealthy: 201-300</div>
   <div style="padding: 30px; background-color: #cf4907; width: 10%; border-radius: 25%; text-align:center; margin-left: 30px">Hazardous: 301+</div>
</div>
<div class="container">
   <div class="row">
      <% @countries.drop(1).each do |country| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
         <div class = "container" style: >
            <div class="card" style="width: 18rem; height: 8rem; margin-bottom: 2rem; text-align: center">
               <div class="card-body" style= "border: 1px solid black">
                  <h5 class="card-title"><%= country.name %></h5>
                  <h6 class="card-subtitle mb-2 text-muted">Year: <%= country.year %></h6>
                  <p class="card-text">Air Quality: <%= country.ghg_amount %> </p>
               </div>
            </div>
         </div>
      </div>
      <%end%>
   </div>
</div>




      
      

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "New Leaf", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About Us", about_us_path, class: "nav-link" %>
      </li>
      
    <% if logged_in? %>
     <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Explore
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Activities", activities_path, class: 'dropdown-item' %>
            <%= link_to "Dashboard", user_path(current_user), class: 'dropdown-item' %>
            <%= link_to "Add an Activity", new_activity_path, class: 'dropdown-item' %>
            <%= link_to "Categories", categories_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
            <%= link_to "Logout", logout_path, data: {"turbo-method": :delete}, class: 'dropdown-item' %>            
          </ul>
        </li>

     <% else %>
     <div class="nav-item">
        <%= link_to "Login", login_path, class: "nav-link" %>
      </div>
      <div class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %> 
      </div>
      <% end %>
      
    </ul>
  </div>
</nav>