config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get '/about-us', to: "pages#about_us"
  get '/sign-up', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users, except: [:new]
  resources :activities do 
    resources :reviews
  end
  resources :categories
  resources :favorites
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user

    has_and_belongs_to_many :categories 
    has_many :reviews
    has_many :favorites
    
    
    validates :name, presence: true, length: {minimum: 2, maximum: 200}
    validates :description, presence: true, length: {minimum: 2, maximum: 400}

    validate :image_path_exists

    def image_path_exists
        
        require 'open-uri'

        begin
            #is url valid 
            #if thrown and exception then rescue will execute 
            path = URI.open(image_path)
            #is response type content image? 
            errors.add(:image_path, "Does not contain image content.") and return unless path.content_type.starts_with?("image")
            
        rescue 
            errors.add(:image_path, "Invalid URL")
        end
    end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :require_same_creator, only: [:destroy, :edit]
  #GET all activities
  def index
    @activities = Activity.all 
  end

  #GET request to create new activity
  def new
    @activity = Activity.new 
  end

  def create
    @activity = helpers.current_user.activities.new(activity_params)

    if @activity.save
      flash[:notice] = "Activity successfully uploaded"
      redirect_to @activity
    else
      flash[:notice] = "There was an error"
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update 
   
    if @activity.update(activity_params)
      flash[:notice] = "Update Successful"
      redirect_to @activity
    else 
      flash[:notice] = "There was an error"
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @favorite = Favorite.find_by(user_id: helpers.current_user.id, activity_id: params[:id])
  end

  def destroy
    @activity.destroy
    redirect_to activities_path

  end

  def save
    helpers.current_user << @activity 
  end

  private 

  def require_same_creator
    if helpers.current_user != @activity.user
      flash[:notice] = "Unauthorized"
      redirect_to helpers.current_user
    end
  end

  def activity_params 
    params.require(:activity).permit(:name, :description, :image_path, category_ids: [])
  end

  def set_activity 
    @activity = Activity.find(params[:id])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    def current_user 
        User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user 
    end
end

app/views/activities/_form.html.erb
<div class= "container" style="background-color: #EB9C5C; padding: 30px;border-radius: 25px; width: 600px">
<%= form_with(model: @activity) do |form|%>
<div class="input-group mb-3">
    <%= form.label :name, class:"input-group-text"%>
    <%= form.text_field :name, class: "form-control" %>
</div>

<div class="input-group">
    <%= form.label :description, class:"input-group-text" %>
    <%= form.text_area :description, class: "form-control" %>
</div>

<label for="basic-url" class="form-label"><%= form.label :image_path %></label>
<div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon3">https://example.com/users/</span>
    <%= form.text_area :image_path, class: "form-control" %>
</div>

<div class="input-group mb-3">
    <span class="input-group-text"><%= form.label :category_id%></span>
    <div class="form-control">
    <%= form.collection_select(:category_ids, Category.all, :id, :name, {}, {multiple: true}) %>
    </div>
</div>
<%= form.submit "Submit", class:"btn btn-secondary", style: "text-align: center" %>
<%end%>
</div>

app/views/activities/create.html.erb
<h1>Activities#create</h1>
<p>Find me in app/views/activities/create.html.erb</p>

app/views/activities/destroy.html.erb
<h1>Activities#destroy</h1>
<p>Find me in app/views/activities/destroy.html.erb</p>

app/views/activities/edit.html.erb
<h1>Edit <%= @activity.name%></h1>

<%= render "form" %>

app/views/activities/index.html.erb
<%= stylesheet_link_tag "activity"%>
<div class="activityPage">
   <div style="text-align:center">
   <h1>Explore all the Activities</h1> 
   </div>
      <div class="row">
         <% @activities.each do |activity| %>
         <div class="col-xs-12 col-md-6 col-lg-4">
         <div class="card" style="width: 90%; margin-bottom: 30px">
               <div>        
                  <%= link_to activity_path(activity) do%>
                  <%= image_tag activity.image_path, class:"card-img-top", style: "border: 1px solid black" %> 
                  <%end%>
               </div>
               <div class="card-body">
                  <h2><b> <%= activity.name %> </b></h2>
                  <p class="card-text">
                     <p>Description: <%= activity.description.slice(0,10) %>....</p>
                  </p>
               </div>
            </div>
         </div>
         <%end%>
      </div>
</div>

app/views/activities/new.html.erb
<img 
   src="https://img.freepik.com/free-vector/illustration-human-avatar-with-environment_53876-17627.jpg?w=826&t=st=1678052551~exp=1678053151~hmac=ff675b48e76ce7815339a51e95b41072d92002d41b308dc140bacc15daf2b851" 
   class="img-fluid" alt="..." 
   style= "
      width:100%;
      height: 90%;
      padding: 1em">

   <div
      class="home" 
      style="
         padding: 1em; 
         width: 30rem; 
         height:15rem; 
         text-align: center; 
         color:#3B3C36;
         position: absolute; 
         top: 300px; 
         margin: auto;
         right: 550px;
         z-index: 1;">
        <h1>Create an Activity</h1>
        <%= render "form" %>
   </div>
</div>

app/views/activities/show.html.erb
<%= stylesheet_link_tag "about"%>
<div class="activityPage">
<%= link_to "Back", activities_path, class:"btn btn-outline-secondary"%>
<div style= "padding:70px">
<div>
</div>
<div class= "container" >
  <div class="row">
    <div class="col-md-6">
      <h1><%= @activity.name%></h1>
          <% if @activity.user %>
          <div> <h3><%= link_to "By #{@activity.user.username}", @activity.user %></h3></div>
         <%end%>
         <h4>Likes: <%= @activity.favorites.count%></h4>
        <div class="card" style="width: 25rem;">
            <%= image_tag @activity.image_path, style: "border: 1px solid black", class:"card-img-top" %> 
          <div class="card-body">
            <p><%= @activity.description%></p>
          </div>
          <% @activity.categories.each do |category| %>
          <ul class="list-group list-group-flush">
                <b><%= category.name%></b>
          </ul>
          <% end %>
        </div>
        <% if current_user == @activity.user%>
        <%= link_to "Edit", edit_activity_path(@activity), class:"btn btn-success"%>
        <%= button_to "Delete", @activity, method: :delete, class:"btn btn-danger" %>
        <%end%>
    </div>
<div class="col-md-6">
<section style="background-color: #f7f6f6;">
          <div class="container my-5 py-5 text-dark">
            <div class="row d-flex justify-content-center">
              <div class="col-md-12 col-lg-10 col-xl-8">
        <div style="text-align: center"><h2>Reviews</h2></div>
        <% @activity.reviews.each do |review| %>
                <div class="card mb-3">
                  <div class="card-body">
                    <div class="d-flex flex-start">
                      <img class="rounded-circle shadow-1-strong me-3"
                        src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" alt="avatar" width="40"
                        height="40" />
                      <div class="w-100">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                          <h6 class="text-primary fw-bold mb-0">
                            <%= review.user.username %>
                            <div>
                            <span class="text-dark ms-2"><%= review.content %></span>
                            </div>
                          </h6>
                          <div>
                            <p class="mb-0"><%= review.date.strftime("%B, %d, %Y") if review.date.present? %></p>
                          </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                          <p class="small mb-0" style="color: #aaa;">
                            <% if current_user == review.user%>
                            <%= link_to "Edit", edit_activity_review_path(review), class:"btn btn-outline-secondary"%>
                            <%= button_to "Delete", activity_review_path(@activity, review), method: :delete, class:"btn btn-outline-danger"%>
                            <%end%>                    
                          </p>
                          
                          <div class="d-flex flex-row">
                            <i class="fas fa-star text-warning me-2"></i>
                            <i class="far fa-check-circle" style="color: #aaa;"></i>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            <% end %>

              </div>
            </div>
          </div>
      <div><p>&nbsp</p></div>
      <%= link_to "Add Review", new_activity_review_path(@activity), 
          class: "btn btn-outline-success",
          style: "position:center"%>
    </section>
</div>
</div>
  </div>
</div>

<%= turbo_frame_tag "first_turbo_frame" do%>
  <%if @favorite.nil?%>
    <%= button_to "Like", favorites_path, params:{favorite:{activity_id:@activity.id}}, method: :post%>
  <%else%>
  <%= button_to "Unlike", favorite_path(@favorite), method: :delete%>
  <%end%>

<%end%>
</div>