config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get '/about-us', to: "pages#about_us"
  get '/sign-up', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users, except: [:new]
  resources :activities do 
    resources :reviews
  end
  resources :categories
  resources :favorites
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = helpers.current_user.reviews.new(review_params)
    activity = Activity.find(params[:activity_id])
    @review.activity_id = params[:activity_id]
    respond_to do |format|
      if @review.save
        format.html { redirect_to activity, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to activity_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:content, :date, :activity_id, :user_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class= 'container' style="padding:30px; background-color: #125E32; border-radius: 15%; width: 45%">
<%= form_with(model: review, url: activity_reviews_path) do |form| %>
  <% if review.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>


<div class="form-floating">
    <%= form.text_area :content, class:"form-control" %>
  <label for="floatingTextarea2"><%= form.label :content%></label>
</div>

<div><p> &nbsp </p></div>

<div class="form-floating" style="margin-bottom: 30px">
    <%= form.text_field :date, value: Time.now.strftime("%A, %B, %d, %Y"), readonly: :true, class: "form-control" %>
  <label for="floatingTextarea2"><%= form.label :date%></label>
</div>

<%= form.submit "Submit", class:"btn btn-success"%>

<% end %>
</div>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Content:</strong>
    <%= review.content %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= review.date %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= review.activity_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= review.user_id %>
  </p>

</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reviews</h1>

<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div style= "text-align: center; margin-top: 30px">
<h1>New review</h1>
</div>

<%= render "form", review: @review %>

<br>

  <%= link_to "Back", activities_path, class: "btn btn-danger"%>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_review_path(@review) %> |
  <%= link_to "Back to reviews", reviews_path %>

  <%= button_to "Destroy this review", @review, method: :delete %>
</div>